spring.datasource.url=jdbc:mysql://localhost:3306/capstone
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
security.jwt.token.secret-key=VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
security.jwt.token.expire-length=1800000
encryption.pbkdf2.salt=your_salt_value
encryption.pbkdf2.iteration-count=10000
encryption.pbkdf2.key-length=256
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
openai.api-key = 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