api:
  base-url: "http://apis.data.go.kr/1471000/FoodNtrCpntDbInfo02"
  apikey: "m1iXnydGfYQrBoqmvQd6l7EUn39kd9XLBDoK6mx00W/hzHe2w77aEFqTohNlwjN3fG2pBR2Tnweqc471CsF5ig=="
naver:
  news:
    client-id: NFBCiQPMAwQTeOfJDxB1
    client-secret: HlME8WFALO
    url: https://openapi.naver.com/v1/search/news
  images:
    client-id: NFBCiQPMAwQTeOfJDxB1
    client-secret: HlME8WFALO
    url: https://openapi.naver.com/v1/search/image
google:
  api:
    key: AIzaSyBY9D2ba6YGabH9rzbFynfDSXvnnn-Zduo
    cx: b6434f9baf7ae44e6